// ═══════════════════════════════════════════════════════════════════════
// FILE : Payment.java
// UC   : UC-05 – Process Payment and Generate Invoice
// LAYER: Entity (maps to the "payments" table in MySQL)
//
// Records every payment attempt against a reservation.
// A reservation can have MULTIPLE payments (retries, partial payments, refunds).
// ═══════════════════════════════════════════════════════════════════════
package com.hotel.reservationsystem.entity;

// ── IMPORT EXPLANATIONS ─────────────────────────────────────────────────
// @JsonIgnore        – Hides a field/method from JSON serialization.
// PaymentMethod      – Enum: CREDIT_CARD, DEBIT_CARD, BANK_TRANSFER, CASH.
// PaymentStatus      – Enum: PENDING, SUCCESS, FAILED, REFUNDED, PARTIALLY_REFUNDED.
// @ManyToOne         – JPA: many payments can belong to one reservation/user.
// FetchType.LAZY     – Related entity loaded on-demand (performance optimization).
// @JoinColumn        – Specifies the foreign key column name.
// @Transient         – Not stored in DB; computed in Java.
// @PrePersist        – Lifecycle callback: runs before INSERT.
// BigDecimal         – Precise decimal for money (avoids float/double rounding).
// LocalDateTime      – Timestamp with date and time.
// ─────────────────────────────────────────────────────────────────────────
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.hotel.reservationsystem.entity.enums.PaymentMethod;
import com.hotel.reservationsystem.entity.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity                        // JPA entity → maps to a database table.
@Table(name = "payments")      // MySQL table name.
@Data                          // Lombok: getters + setters + toString + equals + hashCode.
@NoArgsConstructor             // Lombok: empty constructor.
@AllArgsConstructor            // Lombok: all-fields constructor.
public class Payment {

    @Id  // Primary key.
    @GeneratedValue(strategy = GenerationType.IDENTITY)  // Auto-increment.
    private Long id;

    // Unique transaction reference, e.g. "TXN-A1B2C3D4E5F6".
    // Generated by the system when a payment is processed.
    @Column(nullable = false, unique = true, length = 40)
    private String transactionReference;

    // @ManyToOne – many payments can belong to ONE reservation.
    //   → A customer might pay in instalments or retry after a failure.
    // Nullable because it could be a buffet reservation instead.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reservation_id", nullable = true)
    private Reservation reservation;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "buffet_reservation_id", nullable = true)
    private BuffetReservation buffetReservation;

    // The staff member who processed this payment (null for online payments).
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "processed_by_user_id")
    private User processedBy;

    // Amount of money in this payment.
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    // How the payment was made.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentMethod paymentMethod;

    // Current status of this payment.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentStatus status = PaymentStatus.PENDING;

    // Masked card number, bank reference, or "Cash received at front desk".
    // NEVER stores full card numbers or CVV (PCI compliance).
    @Column(length = 100)
    private String paymentReferenceInfo;

    // If payment failed, the reason is stored here (e.g. "Card declined").
    @Column(length = 255)
    private String failureReason;

    // Front desk payment verification (NULL = not yet verified by staff).
    @Column(name = "verified_at")
    private LocalDateTime verifiedAt;

    @Column(name = "verified_by", length = 100)
    private String verifiedBy;

    // Timestamp when the payment was made.
    @Column(nullable = false, updatable = false)
    private LocalDateTime paidAt = LocalDateTime.now();

    // @PrePersist – sets the timestamp before the first INSERT.
    @PrePersist
    protected void onCreate() {
        this.paidAt = LocalDateTime.now();
    }

    // Alias for UC-06 (Reports) which accesses paymentMethod as "method".
    @Transient
    @JsonIgnore
    public PaymentMethod getMethod() {
        return paymentMethod;
    }
}
